package model;
// Generated 24-sep-2016 0:39:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ComprobanteVenta generated by hbm2java
 */
public class ComprobanteVenta  implements java.io.Serializable {


     private BigDecimal idOrden;
     private String ruc;
     private String nombreEmpresa;
     private String nombreCliente;
     private BigDecimal montoTotal;
     private Date fechaRegistro;

    public ComprobanteVenta() {
    }

    public ComprobanteVenta(BigDecimal idOrden, String ruc, String nombreEmpresa, String nombreCliente, BigDecimal montoTotal, Date fechaRegistro) {
       this.idOrden = idOrden;
       this.ruc = ruc;
       this.nombreEmpresa = nombreEmpresa;
       this.nombreCliente = nombreCliente;
       this.montoTotal = montoTotal;
       this.fechaRegistro = fechaRegistro;
    }
   
    public BigDecimal getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(BigDecimal idOrden) {
        this.idOrden = idOrden;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


