package model;
// Generated 24-sep-2016 0:39:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleComprobante generated by hbm2java
 */
public class DetalleComprobante  implements java.io.Serializable {


     private BigDecimal idDetalle;
     private BigDecimal cantidad;
     private String producto;
     private BigDecimal precioUnitario;
     private BigDecimal precioParcial;
     private BigDecimal comprobanteVentaIdOrden;

    public DetalleComprobante() {
    }

    public DetalleComprobante(BigDecimal idDetalle, BigDecimal cantidad, String producto, BigDecimal precioUnitario, BigDecimal precioParcial, BigDecimal comprobanteVentaIdOrden) {
       this.idDetalle = idDetalle;
       this.cantidad = cantidad;
       this.producto = producto;
       this.precioUnitario = precioUnitario;
       this.precioParcial = precioParcial;
       this.comprobanteVentaIdOrden = comprobanteVentaIdOrden;
    }
   
    public BigDecimal getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getPrecioParcial() {
        return this.precioParcial;
    }
    
    public void setPrecioParcial(BigDecimal precioParcial) {
        this.precioParcial = precioParcial;
    }
    public BigDecimal getComprobanteVentaIdOrden() {
        return this.comprobanteVentaIdOrden;
    }
    
    public void setComprobanteVentaIdOrden(BigDecimal comprobanteVentaIdOrden) {
        this.comprobanteVentaIdOrden = comprobanteVentaIdOrden;
    }




}


