package model;
// Generated 24-sep-2016 0:39:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * LogComprobante generated by hbm2java
 */
public class LogComprobante  implements java.io.Serializable {


     private BigDecimal idLogComprobante;
     private String usuario;
     private Blob evento;
     private Date fechaRegistro;
     private String ip;

    public LogComprobante() {
    }

    public LogComprobante(BigDecimal idLogComprobante, String usuario, Blob evento, Date fechaRegistro, String ip) {
       this.idLogComprobante = idLogComprobante;
       this.usuario = usuario;
       this.evento = evento;
       this.fechaRegistro = fechaRegistro;
       this.ip = ip;
    }
   
    public BigDecimal getIdLogComprobante() {
        return this.idLogComprobante;
    }
    
    public void setIdLogComprobante(BigDecimal idLogComprobante) {
        this.idLogComprobante = idLogComprobante;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Blob getEvento() {
        return this.evento;
    }
    
    public void setEvento(Blob evento) {
        this.evento = evento;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


